server:
  port: ${PORT:8081}
  servlet:
    context-path: /api
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    #    web: debug
    com.tdubuis: debug
spring:
  application:
    name: AuthApp
#  sql:
#    init:
#      mode: always #For generate fakeData with data.sql file
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/authapp}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    #      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
